# 张量基础操作

In [ ]:
import torch 

1. 1维张量

In [43]:
points = torch.tensor([1.0, 4.0, 2.0, 1.0, 3.0, 5.0]) # 1D tensor with 6
points

tensor([1., 4., 2., 1., 3., 5.])

索引和切片

In [41]:
points[0] # first element

tensor(1.)

In [40]:
points[1:4] # second to fourth elements

tensor([4., 2., 1.])

In [44]:
points[1:] # all but the first element

tensor([4., 2., 1., 3., 5.])

In [46]:
points[:4] # first four elements

tensor([1., 4., 2., 1.])

In [45]:
points[::2] # every second element

tensor([1., 2., 3.])

基础信息查看

In [58]:
points.numel() # number of elements

6

In [27]:
points.shape # 6个点

torch.Size([6])

In [28]:
points.type() # dtype

'torch.FloatTensor'

In [47]:
points.dtype # float32

torch.float32

In [29]:
points.view(3,2) # reshape to 3 rows and 2 columns

tensor([[1., 4.],
        [2., 1.],
        [3., 5.]])

In [36]:
points.device # device info

device(type='cpu')

常用函数

In [49]:
torch.sum(points) # sum of all elements

tensor(16.)

In [50]:
torch.min(points) # min of all elements

tensor(1.)

In [51]:
torch.max(points) # max of all elements

tensor(5.)

In [52]:
torch.mean(points) # mean of all elements

tensor(2.6667)

排序

In [53]:
torch.sort(points) # sort elements in ascending order

torch.return_types.sort(
values=tensor([1., 1., 2., 3., 4., 5.]),
indices=tensor([0, 3, 2, 4, 1, 5]))

In [54]:
torch.argmax(points) # index of max element

tensor(5)

In [56]:
torch.argmin(points) # index of min element

tensor(0)

In [57]:
torch.argsort(points) # indices that would sort the tensor

tensor([0, 3, 2, 4, 1, 5])

张量创建

使用特定函数创建张量：
- 全为 0 的张量：torch.zeros(size)
- 全为 1 的张量：torch.ones(size)
- 随机值张量：torch.randn(size)

In [34]:
torch.arange(5) # 1D tensor with values from 0 to 4

tensor([0, 1, 2, 3, 4])

In [35]:
torch.linspace(0,1,5) # 1D tensor with 5 values from 0 to 1

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [7]:
torch.ones(2,3) # 2 rows and 3 columns, all elements are 1

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.zeros(2,3) # 2 rows and 3 columns, all elements are 0

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
torch.randn(2,3) # 2 rows and 3 columns, random numbers from standard normal distribution

tensor([[ 0.0361,  0.4816, -0.4785],
        [-1.0181,  1.1600,  1.6929]])

In [33]:
torch.ones_like(points) # same shape as points, all elements are 1

tensor([1., 1., 1., 1., 1., 1.])

形状操作

In [72]:
a = torch.arange(6) # 1D tensor with values from 0 to 5
a

tensor([0, 1, 2, 3, 4, 5])

In [74]:
a.shape # shape of a

torch.Size([6])

In [73]:
b = a.view(2,3) # reshape to 2 rows and 3 columns
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [75]:
c =a.unbind() # split into individual elements
c

(tensor(0), tensor(1), tensor(2), tensor(3), tensor(4), tensor(5))

In [76]:
c.index(3) # get the 4th element

3

In [78]:
d = b.t() # transpose b
d

tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [80]:
e = b.matmul(d) # matrix multiplication of b and d
e

tensor([[ 5, 14],
        [14, 50]])

In [81]:
f = b + 1 # add 1 to each element of b
f

tensor([[1, 2, 3],
        [4, 5, 6]])

In [83]:
g = b * 2 # multiply each element of b by 2
g

tensor([[ 0,  2,  4],
        [ 6,  8, 10]])

In [85]:
h = b ** 2 # square each element of b
h

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [87]:
i = torch.exp(b) # exponential of each element of b
i

tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5982, 148.4132]])

In [88]:
j = torch.log(h) # natural logarithm of each element of h
j   

tensor([[  -inf, 0.0000, 1.3863],
        [2.1972, 2.7726, 3.2189]])

In [90]:
k = torch.sqrt(h) # square root of each element of h
k

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [92]:
l = torch.sum(b, dim=0) # sum of each column
l

tensor([3, 5, 7])

In [94]:
m = torch.sum(b, dim=1) # sum of each row
m

tensor([ 3, 12])